## Python version 
FROM python:3.11-slim 
### Creating the folder
WORKDIR /fastapi 
COPY requirements-fastapi.txt /fastapi/requirements.txt
COPY src/api/ .
EXPOSE 8000 
CMD [ "python", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
