FROM python:3.11-slim

WORKDIR /fastapi

COPY requirements-fastapi-docker.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY src ./src
COPY datas/processed ./datas/processed
COPY models_saved ./models_saved
EXPOSE 8000

CMD ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]