services:
  fastapi:  ## Service One: Fastapi through render 
    build:  
      context: .
      dockerfile: Dockerfile.fastapi

    ports: 
    - "8000:8000"
    networks:
      - clarity-network 

  streamlit: 
    build: 
      context: . 
      dockerfile: Dockerfile.streamlit
    container_name: streamlit-container
    ports:
    - "8501:8501"
    environment:
      API_URL: http://fastapi:8000
    depends_on:
      - fastapi
    networks:
      - clarity-network

networks:
  clarity-network:
    driver: bridge 