## Python version 
FROM python:3.11-slim 
### Creating the folder
WORKDIR /streamlit

COPY requirements.txt /streamlit/requirements.txt 

RUN pip install --no-cache-dir -r requirements.txt

## Copying the home.py that has streamlit to the working directory 
COPY streamlit/home.py /streamlit

EXPOSE 8501 

CMD ["streamlit", "run", "home.py", "--server.port=8501","--server.address = 0.0.0.0"]
