import torch.nn as nn

class RNN(nn.Module):
    def __init__(self, input_size,hidden_size, dropout_prob = 0.2):
        super().__init__()
        self.rnn = nn.RNN(input_size, hidden_size = hidden_size, batch_first=True)
        ## So rnn expects the input in terms of (batch, timeStep, features) ## Given the number of batches performs the given number of time step so batch1-> timestep1-> Features/neurons 
    
        self.dropout = nn.Dropout(dropout_prob)
        self.fc = nn.Sequential(
            nn.Linear(hidden_size, 64),
            nn.LeakyReLU(negative_slope=0.01),
            nn.Dropout(dropout_prob),
            nn.Linear(64,32),
            nn.LeakyReLU(negative_slope=0.01),
            nn.Dropout(dropout_prob),
            nn.Linear(32,16),
            nn.LeakyReLU(negative_slope=0.01),
            nn.Dropout(dropout_prob),
            nn.Linear(16,1)
        )

    def forward(self, x):
        out, _  = self.rnn(x) ## This returns the output and the hidden state, _ consists of the final state
        out = out[:,-1,:] ## Taking out the last hidden state generated by the RNN 
        out = nn.BatchNorm1d(out) ## Then Batch norm it before sending it to the MLP 
        out = self.fc(out) ## MLP is done 
        return out ## Output is generated 
    
    



